# Generated by Django 4.1.2 on 2022-11-04 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_user_groups_user_user_permissions_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8f90d99-d328-4e83-8165-0e088d3ad003'), editable=False, primary_key=True, serialize=False),
        ),
    ]
