# Generated by Django 4.1.2 on 2022-11-06 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fadc6f37-269b-4050-a0ce-dba77344803d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
